spring.application.name=finpay-api

#DataSource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/fin_pay
spring.datasource.username=charlesmartins
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA Configuration
spring.jpa.hibernate.ddl-auto=none

#HikariCP Settings
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.registerMbeans=true


